import { describe, it, expect } from 'vitest'
import { computeCoachStats } from '@/lib/coach-stats'
import type { Coach, Group, Payment, Enrollment, AttendanceRecord } from '@/types'

const NOW = new Date('2026-08-15T12:00:00')
const PERIOD_START = new Date('2026-08-01T00:00:00')

function makeCoach(overrides: Partial<Coach> = {}): Coach {
  return {
    id: 'coach-1',
    firstName: 'Ana',
    lastName: 'García',
    dni: '00000000A',
    email: 'ana@example.com',
    phone: '600000000',
    hireDate: new Date('2020-01-01'),
    isActive: true,
    createdAt: new Date('2020-01-01'),
    ...overrides,
  }
}

function makeGroup(overrides: Partial<Group> = {}): Group {
  return {
    id: 'group-1',
    name: 'Iniciación',
    level: 'iniciacion',
    coachId: 'coach-1',
    coachName: 'Ana García',
    courtId: 'court-1',
    courtName: 'Pista 1',
    schedule: [{ dayOfWeek: 1, startTime: '18:00', endTime: '19:00' }],
    maxCapacity: 8,
    currentEnrollment: 8,
    defaultTariffId: 't1',
    defaultTariffPrice: 40,
    billingFrequency: 'monthly',
    startDate: new Date('2026-01-01'),
    endDate: new Date('2026-12-31'),
    isActive: true,
    createdAt: new Date('2026-01-01'),
    ...overrides,
  }
}

function makePayment(overrides: Partial<Payment> = {}): Payment {
  return {
    id: 'pay-1',
    playerId: 'p1',
    playerName: 'Jugador',
    groupId: 'group-1',
    concept: 'Cuota mensual',
    amount: 40,
    status: 'pagado',
    billingMonth: 8,
    billingYear: 2026,
    dueDate: new Date('2026-08-01'),
    paidDate: new Date('2026-08-03'),
    autogenerated: true,
    createdAt: new Date('2026-08-01'),
    ...overrides,
  }
}

function makeAttendance(overrides: Partial<AttendanceRecord> = {}): AttendanceRecord {
  return {
    id: 'att-1',
    groupId: 'group-1',
    groupName: 'Iniciación',
    date: new Date('2026-08-03T00:00:00'), // lunes
    records: [],
    coachId: 'coach-1',
    createdAt: new Date('2026-08-03'),
    ...overrides,
  }
}

describe('computeCoachStats', () => {
  it('calcula €/hora a partir de ingresos y horas de asistencia real', () => {
    const coaches = [makeCoach()]
    const groups = [makeGroup()]
    const payments = [makePayment({ amount: 60 })]
    const attendance = [makeAttendance()] // 1h (lunes 18:00-19:00)
    const stats = computeCoachStats(coaches, groups, payments, [], attendance, PERIOD_START, 4, NOW)
    expect(stats).toHaveLength(1)
    expect(stats[0]).toMatchObject({ coachId: 'coach-1', coachName: 'Ana García', hours: 1, rph: 60 })
  })

  it('usa la estimacion por horario si no hay asistencia registrada', () => {
    const coaches = [makeCoach()]
    const groups = [makeGroup()]
    const payments = [makePayment({ amount: 160 })]
    const stats = computeCoachStats(coaches, groups, payments, [], [], PERIOD_START, 4, NOW)
    // 1h/semana x 4 semanas = 4h estimadas
    expect(stats[0].hours).toBe(4)
    expect(stats[0].rph).toBe(40)
  })

  it('calcula retencion a 3 meses correctamente', () => {
    const coaches = [makeCoach()]
    const groups = [makeGroup()]
    const enrollments: Enrollment[] = [
      { id: 'e1', playerId: 'p1', playerName: 'A', groupId: 'group-1', groupName: 'Iniciación', tariffId: 't1', tariffName: 'Mensual', enrollmentDate: new Date('2026-01-01'), isActive: true },
      { id: 'e2', playerId: 'p2', playerName: 'B', groupId: 'group-1', groupName: 'Iniciación', tariffId: 't1', tariffName: 'Mensual', enrollmentDate: new Date('2026-01-01'), isActive: false, unenrollmentDate: new Date('2026-06-01') },
    ]
    const stats = computeCoachStats(coaches, groups, [], enrollments, [], PERIOD_START, 4, NOW)
    expect(stats[0].retentionPct).toBe(50)
  })

  it('excluye entrenadores inactivos', () => {
    const coaches = [makeCoach({ isActive: false })]
    const groups = [makeGroup()]
    const payments = [makePayment()]
    const stats = computeCoachStats(coaches, groups, payments, [], [], PERIOD_START, 4, NOW)
    expect(stats).toHaveLength(0)
  })

  it('excluye entrenadores sin ningun dato (rph=0, hours=0, retencion nula)', () => {
    const coaches = [makeCoach()]
    const stats = computeCoachStats(coaches, [], [], [], [], PERIOD_START, 4, NOW)
    expect(stats).toHaveLength(0)
  })

  it('no estima horas por horario de un grupo cuya endDate ya paso (sin asistencia registrada)', () => {
    const coaches = [makeCoach()]
    const groups = [makeGroup({
      startDate: new Date('2026-01-01'),
      endDate: new Date('2026-07-01'), // ya paso respecto a NOW (2026-08-15)
    })]
    // Una matricula elegible para retencion, para que el coach no quede
    // excluido del todo por el filtro final de computeCoachStats (que
    // descarta entradas con rph=0, hours=0 y retentionPct=null a la vez) -
    // asi se puede comprobar especificamente que `hours` es 0.
    const enrollments: Enrollment[] = [
      { id: 'e1', playerId: 'p1', playerName: 'A', groupId: 'group-1', groupName: 'Iniciación', tariffId: 't1', tariffName: 'Mensual', enrollmentDate: new Date('2026-01-01'), isActive: true },
    ]
    // Sin registros de attendance -> se usaria el fallback hoursFromSchedule
    const stats = computeCoachStats(coaches, groups, [], enrollments, [], PERIOD_START, 4, NOW)
    // El grupo finalizado no aporta horas estimadas (hours=0, por tanto
    // rph=0 segun la formula existente), pero el coach sigue apareciendo
    // porque tiene retencion calculable.
    expect(stats).toHaveLength(1)
    expect(stats[0].hours).toBe(0)
    expect(stats[0].rph).toBe(0)
    expect(stats[0].retentionPct).toBe(100)
  })
})
