// ==========================================
// San Javier Academy Manager - Datos de Demo
// ==========================================

import type {
  Court,
  Tariff,
  Coach,
  Player,
  Group,
  Enrollment,
  Payment,
  Activity,
  AcademyEvent,
  Evaluation,
  CoachSalaryConfig,
} from '@/types'

// ===================
// PISTAS
// ===================
export const demoCourts: Court[] = [
  {
    id: 'court-001',
    name: 'Pista 1 - Central',
    type: 'outdoor',
    surface: 'cristal',
    isActive: true,
    notes: 'Pista principal con iluminación LED',
  },
  {
    id: 'court-002',
    name: 'Pista 2 - Cubierta',
    type: 'indoor',
    surface: 'cristal',
    isActive: true,
    notes: 'Pista cubierta climatizada',
  },
  {
    id: 'court-003',
    name: 'Pista 3 - Exterior',
    type: 'outdoor',
    surface: 'cesped',
    isActive: true,
  },
  {
    id: 'court-004',
    name: 'Pista 4 - Muro',
    type: 'outdoor',
    surface: 'muro',
    isActive: false,
    notes: 'En mantenimiento - renovación de suelo prevista para marzo 2026',
  },
]

// ===================
// TARIFAS
// ===================
export const demoTariffs: Tariff[] = [
  {
    id: 'tariff-001',
    name: 'Adultos 2 días/semana',
    price: 55,
    billingFrequency: 'monthly',
    description: 'Clases para adultos, 2 sesiones semanales de 1.5h',
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'tariff-002',
    name: 'Adultos 1 día/semana',
    price: 35,
    billingFrequency: 'monthly',
    description: 'Clases para adultos, 1 sesión semanal de 1.5h',
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'tariff-003',
    name: 'Adultos 3 días/semana',
    price: 75,
    billingFrequency: 'monthly',
    description: 'Clases para adultos, 3 sesiones semanales de 1.5h',
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'tariff-004',
    name: 'Escuela Menores 2 días/semana',
    price: 45,
    billingFrequency: 'installments',
    installmentMonths: [10, 12, 2, 5],
    description: 'Escuela de menores, 2 sesiones semanales de 1h. Pago fraccionado en 4 cuotas.',
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'tariff-005',
    name: 'Escuela Menores 1 día/semana',
    price: 30,
    billingFrequency: 'installments',
    installmentMonths: [10, 12, 2, 5],
    description: 'Escuela de menores, 1 sesión semanal de 1h. Pago fraccionado en 4 cuotas.',
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'tariff-006',
    name: 'Competición',
    price: 85,
    billingFrequency: 'monthly',
    description: 'Grupo de competición, 3 sesiones semanales de 2h con preparación física',
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
]

// ===================
// ENTRENADORES
// ===================
export const demoCoaches: Coach[] = [
  {
    id: 'coach-001',
    firstName: 'Miguel',
    lastName: 'Fernández López',
    dni: '23456789B',
    email: 'miguel.fernandez@sanjavier.es',
    phone: '600 111 222',
    address: 'Calle Mayor 15, San Javier, Murcia',
    hireDate: new Date('2022-03-15'),
    isActive: true,
    specialization: 'Competición y alto rendimiento',
    certifications: 'Monitor Nacional de Pádel FEP, Preparador Físico nivel 2',
    notes: 'Coordinador de la escuela de competición',
    createdAt: new Date('2022-03-15'),
  },
  {
    id: 'coach-002',
    firstName: 'Laura',
    lastName: 'Martínez Ruiz',
    dni: '34567890C',
    email: 'laura.martinez@sanjavier.es',
    phone: '600 333 444',
    address: 'Avda. de la Libertad 8, Santiago de la Ribera, Murcia',
    hireDate: new Date('2023-09-01'),
    isActive: true,
    specialization: 'Iniciación y menores',
    certifications: 'Monitora Nacional de Pádel FEP, Técnico deportivo TAFAD',
    notes: 'Responsable de la escuela de menores',
    createdAt: new Date('2023-09-01'),
  },
  {
    id: 'coach-003',
    firstName: 'Alejandro',
    lastName: 'Sánchez Navarro',
    dni: '45678901D',
    email: 'alejandro.sanchez@sanjavier.es',
    phone: '600 555 666',
    address: 'Calle San Juan 22, San Javier, Murcia',
    hireDate: new Date('2024-01-10'),
    isActive: true,
    specialization: 'Intermedio y avanzado',
    certifications: 'Monitor Nacional de Pádel FEP',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: 'coach-004',
    firstName: 'Patricia',
    lastName: 'Gómez Herrera',
    dni: '56789012E',
    email: 'patricia.gomez@sanjavier.es',
    phone: '600 777 888',
    address: 'Plaza de España 3, La Manga del Mar Menor, Murcia',
    hireDate: new Date('2024-06-01'),
    isActive: false,
    specialization: 'Iniciación adultos',
    certifications: 'Monitora Regional de Pádel FPRM',
    notes: 'Excedencia por maternidad hasta septiembre 2026',
    createdAt: new Date('2024-06-01'),
  },
]

// ===================
// JUGADORES
// ===================
export const demoPlayers: Player[] = [
  // --- Adultos activos ---
  {
    id: 'player-001',
    firstName: 'Antonio',
    lastName: 'García Pérez',
    dni: '12345678A',
    birthDate: new Date('1985-04-12'),
    email: 'antonio.garcia@email.com',
    phone: '611 001 001',
    address: 'Calle del Mar 5, 2ºB',
    city: 'San Javier',
    postalCode: '30580',
    level: 'intermedio',
    dominantHand: 'derecha',
    position: 'drive',
    previousExperience: '3 años jugando de forma recreativa',
    bankAccountHolder: 'Antonio García Pérez',
    iban: 'ES91 2100 0418 4502 0005 1332',
    status: 'activo',
    registrationDate: new Date('2025-09-15'),
    isMinor: false,
    recoveryCredits: 1,
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-09-15'),
  },
  {
    id: 'player-002',
    firstName: 'María',
    lastName: 'López Hernández',
    dni: '23456789B',
    birthDate: new Date('1990-08-22'),
    email: 'maria.lopez@email.com',
    phone: '611 002 002',
    address: 'Avda. del Mediterráneo 18, 1ºA',
    city: 'San Javier',
    postalCode: '30580',
    level: 'avanzado',
    dominantHand: 'derecha',
    position: 'reves',
    previousExperience: '5 años de competición amateur',
    bankAccountHolder: 'María López Hernández',
    iban: 'ES68 0049 5735 7820 0600 0001',
    status: 'activo',
    registrationDate: new Date('2025-09-10'),
    isMinor: false,
    recoveryCredits: 0,
    createdAt: new Date('2025-09-10'),
    updatedAt: new Date('2025-09-10'),
  },
  {
    id: 'player-003',
    firstName: 'Francisco',
    lastName: 'Martínez Sánchez',
    dni: '34567890C',
    birthDate: new Date('1978-01-30'),
    email: 'fran.martinez@email.com',
    phone: '611 003 003',
    address: 'Calle Colón 42',
    city: 'San Javier',
    postalCode: '30580',
    level: 'iniciacion',
    dominantHand: 'derecha',
    position: 'ambos',
    bankAccountHolder: 'Francisco Martínez Sánchez',
    iban: 'ES17 0081 0200 1500 0100 1234',
    status: 'activo',
    registrationDate: new Date('2025-10-01'),
    isMinor: false,
    recoveryCredits: 0,
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-10-01'),
  },
  {
    id: 'player-004',
    firstName: 'Carmen',
    lastName: 'Ruiz Navarro',
    dni: '45678901D',
    birthDate: new Date('1992-11-05'),
    email: 'carmen.ruiz@email.com',
    phone: '611 004 004',
    address: 'Calle San Fernando 9, 3ºC',
    city: 'Santiago de la Ribera',
    postalCode: '30720',
    level: 'intermedio',
    dominantHand: 'izquierda',
    position: 'reves',
    previousExperience: '2 años de clases en otro club',
    bankAccountHolder: 'Carmen Ruiz Navarro',
    iban: 'ES21 1465 0100 9519 0200 0048',
    status: 'activo',
    registrationDate: new Date('2025-09-20'),
    isMinor: false,
    recoveryCredits: 2,
    createdAt: new Date('2025-09-20'),
    updatedAt: new Date('2025-09-20'),
  },
  {
    id: 'player-005',
    firstName: 'Javier',
    lastName: 'Hernández Torres',
    dni: '56789012E',
    birthDate: new Date('1988-06-18'),
    email: 'javier.hernandez@email.com',
    phone: '611 005 005',
    address: 'Avda. de Murcia 33',
    city: 'San Javier',
    postalCode: '30580',
    level: 'competicion',
    dominantHand: 'derecha',
    position: 'drive',
    previousExperience: '8 años de competición federada',
    medicalNotes: 'Tendinitis codo derecho - controlar carga',
    bankAccountHolder: 'Javier Hernández Torres',
    iban: 'ES80 2310 0001 1800 0012 3456',
    status: 'activo',
    registrationDate: new Date('2025-09-05'),
    isMinor: false,
    recoveryCredits: 0,
    createdAt: new Date('2025-09-05'),
    updatedAt: new Date('2025-09-05'),
  },
  {
    id: 'player-006',
    firstName: 'Ana',
    lastName: 'Serrano Díaz',
    dni: '67890123F',
    birthDate: new Date('1995-03-25'),
    email: 'ana.serrano@email.com',
    phone: '611 006 006',
    address: 'Calle de la Paz 7, bajo A',
    city: 'San Javier',
    postalCode: '30580',
    level: 'iniciacion',
    dominantHand: 'derecha',
    position: 'drive',
    bankAccountHolder: 'Ana Serrano Díaz',
    iban: 'ES12 0182 3456 7890 1234 5678',
    status: 'activo',
    registrationDate: new Date('2025-11-10'),
    isMinor: false,
    recoveryCredits: 0,
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2025-11-10'),
  },
  {
    id: 'player-007',
    firstName: 'Roberto',
    lastName: 'Moreno Castillo',
    dni: '78901234G',
    birthDate: new Date('1982-09-14'),
    email: 'roberto.moreno@email.com',
    phone: '611 007 007',
    address: 'Calle Príncipe de Asturias 21, 4ºD',
    city: 'San Javier',
    postalCode: '30580',
    level: 'competicion',
    dominantHand: 'derecha',
    position: 'reves',
    previousExperience: '10 años competición, ex-jugador profesional regional',
    bankAccountHolder: 'Roberto Moreno Castillo',
    iban: 'ES55 0075 0001 0600 0012 3456',
    status: 'activo',
    registrationDate: new Date('2025-09-05'),
    isMinor: false,
    recoveryCredits: 1,
    createdAt: new Date('2025-09-05'),
    updatedAt: new Date('2025-09-05'),
  },
  {
    id: 'player-008',
    firstName: 'Isabel',
    lastName: 'Vega Romero',
    dni: '89012345H',
    birthDate: new Date('1998-12-01'),
    email: 'isabel.vega@email.com',
    phone: '611 008 008',
    address: 'Paseo de la Estación 14',
    city: 'San Javier',
    postalCode: '30580',
    level: 'avanzado',
    dominantHand: 'derecha',
    position: 'drive',
    previousExperience: '4 años en escuela de pádel',
    bankAccountHolder: 'Isabel Vega Romero',
    iban: 'ES33 2085 0100 1203 1234 5678',
    status: 'activo',
    registrationDate: new Date('2025-10-15'),
    isMinor: false,
    recoveryCredits: 0,
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2025-10-15'),
  },
  // --- Menores con tutores ---
  {
    id: 'player-009',
    firstName: 'Pablo',
    lastName: 'Jiménez Ortega',
    dni: '',
    birthDate: new Date('2013-05-20'),
    email: 'familia.jimenez@email.com',
    phone: '611 009 009',
    address: 'Calle Rosalía de Castro 4, 1ºB',
    city: 'San Javier',
    postalCode: '30580',
    level: 'menores',
    dominantHand: 'derecha',
    position: 'ambos',
    bankAccountHolder: 'Luis Jiménez Martín',
    iban: 'ES44 0128 0001 2345 6789 0123',
    status: 'activo',
    registrationDate: new Date('2025-09-15'),
    isMinor: true,
    guardian: {
      firstName: 'Luis',
      lastName: 'Jiménez Martín',
      dni: '90123456I',
      phone: '611 109 009',
      email: 'luis.jimenez@email.com',
      relationship: 'padre',
    },
    recoveryCredits: 0,
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-09-15'),
  },
  {
    id: 'player-010',
    firstName: 'Lucía',
    lastName: 'Navarro Gil',
    dni: '',
    birthDate: new Date('2014-08-11'),
    email: 'familia.navarro@email.com',
    phone: '611 010 010',
    address: 'Avda. del Mar Menor 50',
    city: 'Santiago de la Ribera',
    postalCode: '30720',
    level: 'menores',
    dominantHand: 'derecha',
    position: 'drive',
    bankAccountHolder: 'Marta Gil Soriano',
    iban: 'ES77 0030 1001 0000 1234 5678',
    status: 'activo',
    registrationDate: new Date('2025-09-15'),
    isMinor: true,
    guardian: {
      firstName: 'Marta',
      lastName: 'Gil Soriano',
      dni: '01234567J',
      phone: '611 110 010',
      email: 'marta.gil@email.com',
      relationship: 'madre',
    },
    recoveryCredits: 1,
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-09-15'),
  },
  {
    id: 'player-011',
    firstName: 'Daniel',
    lastName: 'Castro Molina',
    dni: '',
    birthDate: new Date('2012-02-28'),
    email: 'familia.castro@email.com',
    phone: '611 011 011',
    address: 'Calle San Blas 17',
    city: 'San Javier',
    postalCode: '30580',
    level: 'menores',
    dominantHand: 'izquierda',
    position: 'reves',
    medicalNotes: 'Alergia al polen - llevar medicación en primavera',
    bankAccountHolder: 'Pedro Castro López',
    iban: 'ES09 0049 1804 1023 4567 8901',
    status: 'activo',
    registrationDate: new Date('2025-10-01'),
    isMinor: true,
    guardian: {
      firstName: 'Pedro',
      lastName: 'Castro López',
      dni: '12345098K',
      phone: '611 111 011',
      email: 'pedro.castro@email.com',
      relationship: 'padre',
    },
    recoveryCredits: 0,
    createdAt: new Date('2025-10-01'),
    updatedAt: new Date('2025-10-01'),
  },
  // --- Lista de espera ---
  {
    id: 'player-012',
    firstName: 'Elena',
    lastName: 'Flores Ramos',
    dni: '21098765L',
    birthDate: new Date('1993-07-09'),
    email: 'elena.flores@email.com',
    phone: '611 012 012',
    address: 'Calle Velázquez 6',
    city: 'San Javier',
    postalCode: '30580',
    level: 'intermedio',
    dominantHand: 'derecha',
    position: 'ambos',
    bankAccountHolder: 'Elena Flores Ramos',
    iban: 'ES62 2100 5731 1102 0000 1234',
    status: 'lista_espera',
    registrationDate: new Date('2026-01-08'),
    isMinor: false,
    recoveryCredits: 0,
    notes: 'Interesada en grupo de intermedio martes y jueves. Viene de club en Cartagena.',
    createdAt: new Date('2026-01-08'),
    updatedAt: new Date('2026-01-08'),
  },
]

// ===================
// GRUPOS
// ===================
export const demoGroups: Group[] = [
  {
    id: 'group-001',
    name: 'Iniciación Adultos - Lunes/Miércoles',
    level: 'iniciacion',
    coachId: 'coach-003',
    coachName: 'Alejandro Sánchez Navarro',
    courtId: 'court-001',
    courtName: 'Pista 1 - Central',
    schedule: [
      { dayOfWeek: 1, startTime: '10:00', endTime: '11:30' },
      { dayOfWeek: 3, startTime: '10:00', endTime: '11:30' },
    ],
    maxCapacity: 4,
    currentEnrollment: 2,
    defaultTariffId: 'tariff-001',
    defaultTariffPrice: 55,
    billingFrequency: 'monthly',
    startDate: new Date('2025-09-15'),
    endDate: new Date('2026-06-30'),
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'group-002',
    name: 'Intermedio - Martes/Jueves',
    level: 'intermedio',
    coachId: 'coach-003',
    coachName: 'Alejandro Sánchez Navarro',
    courtId: 'court-002',
    courtName: 'Pista 2 - Cubierta',
    schedule: [
      { dayOfWeek: 2, startTime: '18:00', endTime: '19:30' },
      { dayOfWeek: 4, startTime: '18:00', endTime: '19:30' },
    ],
    maxCapacity: 4,
    currentEnrollment: 2,
    defaultTariffId: 'tariff-001',
    defaultTariffPrice: 55,
    billingFrequency: 'monthly',
    startDate: new Date('2025-09-15'),
    endDate: new Date('2026-06-30'),
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'group-003',
    name: 'Avanzado - Lunes/Miércoles/Viernes',
    level: 'avanzado',
    coachId: 'coach-001',
    coachName: 'Miguel Fernández López',
    courtId: 'court-001',
    courtName: 'Pista 1 - Central',
    schedule: [
      { dayOfWeek: 1, startTime: '19:00', endTime: '20:30' },
      { dayOfWeek: 3, startTime: '19:00', endTime: '20:30' },
      { dayOfWeek: 5, startTime: '19:00', endTime: '20:30' },
    ],
    maxCapacity: 4,
    currentEnrollment: 2,
    defaultTariffId: 'tariff-003',
    defaultTariffPrice: 75,
    billingFrequency: 'monthly',
    startDate: new Date('2025-09-15'),
    endDate: new Date('2026-06-30'),
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'group-004',
    name: 'Competición - Martes/Jueves/Viernes',
    level: 'competicion',
    coachId: 'coach-001',
    coachName: 'Miguel Fernández López',
    courtId: 'court-002',
    courtName: 'Pista 2 - Cubierta',
    schedule: [
      { dayOfWeek: 2, startTime: '20:00', endTime: '22:00' },
      { dayOfWeek: 4, startTime: '20:00', endTime: '22:00' },
      { dayOfWeek: 5, startTime: '20:00', endTime: '22:00' },
    ],
    maxCapacity: 4,
    currentEnrollment: 2,
    defaultTariffId: 'tariff-006',
    defaultTariffPrice: 85,
    billingFrequency: 'monthly',
    startDate: new Date('2025-09-15'),
    endDate: new Date('2026-06-30'),
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'group-005',
    name: 'Escuela Menores - Lunes/Miércoles',
    level: 'menores',
    coachId: 'coach-002',
    coachName: 'Laura Martínez Ruiz',
    courtId: 'court-003',
    courtName: 'Pista 3 - Exterior',
    schedule: [
      { dayOfWeek: 1, startTime: '17:00', endTime: '18:00' },
      { dayOfWeek: 3, startTime: '17:00', endTime: '18:00' },
    ],
    maxCapacity: 4,
    currentEnrollment: 3,
    defaultTariffId: 'tariff-004',
    defaultTariffPrice: 45,
    billingFrequency: 'installments',
    installmentMonths: [10, 12, 2, 5],
    startDate: new Date('2025-09-15'),
    endDate: new Date('2026-06-30'),
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
  {
    id: 'group-006',
    name: 'Iniciación Adultos - Viernes',
    level: 'iniciacion',
    coachId: 'coach-002',
    coachName: 'Laura Martínez Ruiz',
    courtId: 'court-003',
    courtName: 'Pista 3 - Exterior',
    schedule: [
      { dayOfWeek: 5, startTime: '10:00', endTime: '11:30' },
    ],
    maxCapacity: 4,
    currentEnrollment: 1,
    defaultTariffId: 'tariff-002',
    defaultTariffPrice: 35,
    billingFrequency: 'monthly',
    startDate: new Date('2025-09-15'),
    endDate: new Date('2026-06-30'),
    isActive: true,
    createdAt: new Date('2025-09-01'),
  },
]

// ===================
// INSCRIPCIONES
// ===================
export const demoEnrollments: Enrollment[] = [
  // Grupo 1: Iniciación L/X -> Francisco, Ana (2 players cancelled = we add a cancelled one too)
  {
    id: 'enroll-001',
    playerId: 'player-003',
    playerName: 'Francisco Martínez Sánchez',
    groupId: 'group-001',
    groupName: 'Iniciación Adultos - Lunes/Miércoles',
    tariffId: 'tariff-001',
    tariffName: 'Adultos 2 días/semana',
    enrollmentDate: new Date('2025-10-01'),
    isActive: true,
  },
  {
    id: 'enroll-002',
    playerId: 'player-006',
    playerName: 'Ana Serrano Díaz',
    groupId: 'group-001',
    groupName: 'Iniciación Adultos - Lunes/Miércoles',
    tariffId: 'tariff-001',
    tariffName: 'Adultos 2 días/semana',
    enrollmentDate: new Date('2025-11-10'),
    isActive: true,
  },
  // Grupo 2: Intermedio M/J -> Antonio, Carmen
  {
    id: 'enroll-003',
    playerId: 'player-001',
    playerName: 'Antonio García Pérez',
    groupId: 'group-002',
    groupName: 'Intermedio - Martes/Jueves',
    tariffId: 'tariff-001',
    tariffName: 'Adultos 2 días/semana',
    enrollmentDate: new Date('2025-09-15'),
    isActive: true,
  },
  {
    id: 'enroll-004',
    playerId: 'player-004',
    playerName: 'Carmen Ruiz Navarro',
    groupId: 'group-002',
    groupName: 'Intermedio - Martes/Jueves',
    tariffId: 'tariff-001',
    tariffName: 'Adultos 2 días/semana',
    customPrice: 50,
    enrollmentDate: new Date('2025-09-20'),
    isActive: true,
  },
  // Grupo 3: Avanzado L/X/V -> María, Isabel
  {
    id: 'enroll-005',
    playerId: 'player-002',
    playerName: 'María López Hernández',
    groupId: 'group-003',
    groupName: 'Avanzado - Lunes/Miércoles/Viernes',
    tariffId: 'tariff-003',
    tariffName: 'Adultos 3 días/semana',
    enrollmentDate: new Date('2025-09-10'),
    isActive: true,
  },
  {
    id: 'enroll-006',
    playerId: 'player-008',
    playerName: 'Isabel Vega Romero',
    groupId: 'group-003',
    groupName: 'Avanzado - Lunes/Miércoles/Viernes',
    tariffId: 'tariff-003',
    tariffName: 'Adultos 3 días/semana',
    enrollmentDate: new Date('2025-10-15'),
    isActive: true,
  },
  // Grupo 4: Competición M/J/V -> Javier, Roberto
  {
    id: 'enroll-007',
    playerId: 'player-005',
    playerName: 'Javier Hernández Torres',
    groupId: 'group-004',
    groupName: 'Competición - Martes/Jueves/Viernes',
    tariffId: 'tariff-006',
    tariffName: 'Competición',
    enrollmentDate: new Date('2025-09-05'),
    isActive: true,
  },
  {
    id: 'enroll-008',
    playerId: 'player-007',
    playerName: 'Roberto Moreno Castillo',
    groupId: 'group-004',
    groupName: 'Competición - Martes/Jueves/Viernes',
    tariffId: 'tariff-006',
    tariffName: 'Competición',
    enrollmentDate: new Date('2025-09-05'),
    isActive: true,
  },
  // Grupo 5: Menores L/X -> Pablo, Lucía, Daniel
  {
    id: 'enroll-009',
    playerId: 'player-009',
    playerName: 'Pablo Jiménez Ortega',
    groupId: 'group-005',
    groupName: 'Escuela Menores - Lunes/Miércoles',
    tariffId: 'tariff-004',
    tariffName: 'Escuela Menores 2 días/semana',
    enrollmentDate: new Date('2025-09-15'),
    isActive: true,
  },
  {
    id: 'enroll-010',
    playerId: 'player-010',
    playerName: 'Lucía Navarro Gil',
    groupId: 'group-005',
    groupName: 'Escuela Menores - Lunes/Miércoles',
    tariffId: 'tariff-004',
    tariffName: 'Escuela Menores 2 días/semana',
    enrollmentDate: new Date('2025-09-15'),
    isActive: true,
  },
  {
    id: 'enroll-011',
    playerId: 'player-011',
    playerName: 'Daniel Castro Molina',
    groupId: 'group-005',
    groupName: 'Escuela Menores - Lunes/Miércoles',
    tariffId: 'tariff-004',
    tariffName: 'Escuela Menores 2 días/semana',
    customPrice: 40,
    enrollmentDate: new Date('2025-10-01'),
    isActive: true,
  },
  // Grupo 6: Iniciación V -> Ana (second enrollment, 1 day)
  // Actually Ana is already in group-001. Let's use a different arrangement.
  // Group 6 has 1 enrollment only, keeping currentEnrollment = 1 matching above
  {
    id: 'enroll-012',
    playerId: 'player-003',
    playerName: 'Francisco Martínez Sánchez',
    groupId: 'group-006',
    groupName: 'Iniciación Adultos - Viernes',
    tariffId: 'tariff-002',
    tariffName: 'Adultos 1 día/semana',
    enrollmentDate: new Date('2025-10-01'),
    isActive: true,
  },
]

// ===================
// PAGOS
// ===================
const now = new Date()
const currentMonth = now.getMonth() + 1
const currentYear = now.getFullYear()
const prevMonth = currentMonth === 1 ? 12 : currentMonth - 1
const prevYear = currentMonth === 1 ? currentYear - 1 : currentYear

export const demoPayments: Payment[] = [
  // --- Pagos del mes anterior (todos pagados) ---
  {
    id: 'pay-001',
    playerId: 'player-001',
    playerName: 'Antonio García Pérez',
    groupId: 'group-002',
    groupName: 'Intermedio - Martes/Jueves',
    enrollmentId: 'enroll-003',
    concept: `Cuota Intermedio - Martes/Jueves (${prevMonth}/${prevYear})`,
    amount: 55,
    status: 'pagado',
    billingMonth: prevMonth,
    billingYear: prevYear,
    dueDate: new Date(prevYear, prevMonth - 1, 5),
    paidDate: new Date(prevYear, prevMonth - 1, 3),
    paymentMethod: 'domiciliacion',
    autogenerated: true,
    createdAt: new Date(prevYear, prevMonth - 1, 1),
  },
  {
    id: 'pay-002',
    playerId: 'player-004',
    playerName: 'Carmen Ruiz Navarro',
    groupId: 'group-002',
    groupName: 'Intermedio - Martes/Jueves',
    enrollmentId: 'enroll-004',
    concept: `Cuota Intermedio - Martes/Jueves (${prevMonth}/${prevYear})`,
    amount: 50,
    status: 'pagado',
    billingMonth: prevMonth,
    billingYear: prevYear,
    dueDate: new Date(prevYear, prevMonth - 1, 5),
    paidDate: new Date(prevYear, prevMonth - 1, 4),
    paymentMethod: 'transferencia',
    autogenerated: true,
    createdAt: new Date(prevYear, prevMonth - 1, 1),
  },
  {
    id: 'pay-003',
    playerId: 'player-002',
    playerName: 'María López Hernández',
    groupId: 'group-003',
    groupName: 'Avanzado - Lunes/Miércoles/Viernes',
    enrollmentId: 'enroll-005',
    concept: `Cuota Avanzado - Lunes/Miércoles/Viernes (${prevMonth}/${prevYear})`,
    amount: 75,
    status: 'pagado',
    billingMonth: prevMonth,
    billingYear: prevYear,
    dueDate: new Date(prevYear, prevMonth - 1, 5),
    paidDate: new Date(prevYear, prevMonth - 1, 2),
    paymentMethod: 'domiciliacion',
    autogenerated: true,
    createdAt: new Date(prevYear, prevMonth - 1, 1),
  },
  {
    id: 'pay-004',
    playerId: 'player-005',
    playerName: 'Javier Hernández Torres',
    groupId: 'group-004',
    groupName: 'Competición - Martes/Jueves/Viernes',
    enrollmentId: 'enroll-007',
    concept: `Cuota Competición - Martes/Jueves/Viernes (${prevMonth}/${prevYear})`,
    amount: 85,
    status: 'pagado',
    billingMonth: prevMonth,
    billingYear: prevYear,
    dueDate: new Date(prevYear, prevMonth - 1, 5),
    paidDate: new Date(prevYear, prevMonth - 1, 5),
    paymentMethod: 'tarjeta',
    autogenerated: true,
    createdAt: new Date(prevYear, prevMonth - 1, 1),
  },
  {
    id: 'pay-005',
    playerId: 'player-007',
    playerName: 'Roberto Moreno Castillo',
    groupId: 'group-004',
    groupName: 'Competición - Martes/Jueves/Viernes',
    enrollmentId: 'enroll-008',
    concept: `Cuota Competición - Martes/Jueves/Viernes (${prevMonth}/${prevYear})`,
    amount: 85,
    status: 'pagado',
    billingMonth: prevMonth,
    billingYear: prevYear,
    dueDate: new Date(prevYear, prevMonth - 1, 5),
    paidDate: new Date(prevYear, prevMonth - 1, 4),
    paymentMethod: 'efectivo',
    autogenerated: true,
    createdAt: new Date(prevYear, prevMonth - 1, 1),
  },
  {
    id: 'pay-006',
    playerId: 'player-003',
    playerName: 'Francisco Martínez Sánchez',
    groupId: 'group-001',
    groupName: 'Iniciación Adultos - Lunes/Miércoles',
    enrollmentId: 'enroll-001',
    concept: `Cuota Iniciación Adultos - Lunes/Miércoles (${prevMonth}/${prevYear})`,
    amount: 55,
    status: 'pagado',
    billingMonth: prevMonth,
    billingYear: prevYear,
    dueDate: new Date(prevYear, prevMonth - 1, 5),
    paidDate: new Date(prevYear, prevMonth - 1, 3),
    paymentMethod: 'domiciliacion',
    autogenerated: true,
    createdAt: new Date(prevYear, prevMonth - 1, 1),
  },
  // --- Pagos del mes actual (mezcla de pendientes y pagados) ---
  {
    id: 'pay-007',
    playerId: 'player-001',
    playerName: 'Antonio García Pérez',
    groupId: 'group-002',
    groupName: 'Intermedio - Martes/Jueves',
    enrollmentId: 'enroll-003',
    concept: `Cuota Intermedio - Martes/Jueves (${currentMonth}/${currentYear})`,
    amount: 55,
    status: 'pagado',
    billingMonth: currentMonth,
    billingYear: currentYear,
    dueDate: new Date(currentYear, currentMonth - 1, 5),
    paidDate: new Date(currentYear, currentMonth - 1, 2),
    paymentMethod: 'domiciliacion',
    autogenerated: true,
    createdAt: new Date(currentYear, currentMonth - 1, 1),
  },
  {
    id: 'pay-008',
    playerId: 'player-004',
    playerName: 'Carmen Ruiz Navarro',
    groupId: 'group-002',
    groupName: 'Intermedio - Martes/Jueves',
    enrollmentId: 'enroll-004',
    concept: `Cuota Intermedio - Martes/Jueves (${currentMonth}/${currentYear})`,
    amount: 50,
    status: 'pendiente',
    billingMonth: currentMonth,
    billingYear: currentYear,
    dueDate: new Date(currentYear, currentMonth - 1, 5),
    autogenerated: true,
    createdAt: new Date(currentYear, currentMonth - 1, 1),
  },
  {
    id: 'pay-009',
    playerId: 'player-002',
    playerName: 'María López Hernández',
    groupId: 'group-003',
    groupName: 'Avanzado - Lunes/Miércoles/Viernes',
    enrollmentId: 'enroll-005',
    concept: `Cuota Avanzado - Lunes/Miércoles/Viernes (${currentMonth}/${currentYear})`,
    amount: 75,
    status: 'pagado',
    billingMonth: currentMonth,
    billingYear: currentYear,
    dueDate: new Date(currentYear, currentMonth - 1, 5),
    paidDate: new Date(currentYear, currentMonth - 1, 3),
    paymentMethod: 'domiciliacion',
    autogenerated: true,
    createdAt: new Date(currentYear, currentMonth - 1, 1),
  },
  {
    id: 'pay-010',
    playerId: 'player-008',
    playerName: 'Isabel Vega Romero',
    groupId: 'group-003',
    groupName: 'Avanzado - Lunes/Miércoles/Viernes',
    enrollmentId: 'enroll-006',
    concept: `Cuota Avanzado - Lunes/Miércoles/Viernes (${currentMonth}/${currentYear})`,
    amount: 75,
    status: 'pendiente',
    billingMonth: currentMonth,
    billingYear: currentYear,
    dueDate: new Date(currentYear, currentMonth - 1, 5),
    autogenerated: true,
    createdAt: new Date(currentYear, currentMonth - 1, 1),
  },
  {
    id: 'pay-011',
    playerId: 'player-005',
    playerName: 'Javier Hernández Torres',
    groupId: 'group-004',
    groupName: 'Competición - Martes/Jueves/Viernes',
    enrollmentId: 'enroll-007',
    concept: `Cuota Competición - Martes/Jueves/Viernes (${currentMonth}/${currentYear})`,
    amount: 85,
    status: 'pendiente',
    billingMonth: currentMonth,
    billingYear: currentYear,
    dueDate: new Date(currentYear, currentMonth - 1, 5),
    autogenerated: true,
    createdAt: new Date(currentYear, currentMonth - 1, 1),
  },
  {
    id: 'pay-012',
    playerId: 'player-007',
    playerName: 'Roberto Moreno Castillo',
    groupId: 'group-004',
    groupName: 'Competición - Martes/Jueves/Viernes',
    enrollmentId: 'enroll-008',
    concept: `Cuota Competición - Martes/Jueves/Viernes (${currentMonth}/${currentYear})`,
    amount: 85,
    status: 'pagado',
    billingMonth: currentMonth,
    billingYear: currentYear,
    dueDate: new Date(currentYear, currentMonth - 1, 5),
    paidDate: new Date(currentYear, currentMonth - 1, 4),
    paymentMethod: 'efectivo',
    autogenerated: true,
    createdAt: new Date(currentYear, currentMonth - 1, 1),
  },
  {
    id: 'pay-013',
    playerId: 'player-003',
    playerName: 'Francisco Martínez Sánchez',
    groupId: 'group-001',
    groupName: 'Iniciación Adultos - Lunes/Miércoles',
    enrollmentId: 'enroll-001',
    concept: `Cuota Iniciación Adultos - Lunes/Miércoles (${currentMonth}/${currentYear})`,
    amount: 55,
    status: 'pendiente',
    billingMonth: currentMonth,
    billingYear: currentYear,
    dueDate: new Date(currentYear, currentMonth - 1, 5),
    autogenerated: true,
    createdAt: new Date(currentYear, currentMonth - 1, 1),
  },
  {
    id: 'pay-014',
    playerId: 'player-006',
    playerName: 'Ana Serrano Díaz',
    groupId: 'group-001',
    groupName: 'Iniciación Adultos - Lunes/Miércoles',
    enrollmentId: 'enroll-002',
    concept: `Cuota Iniciación Adultos - Lunes/Miércoles (${currentMonth}/${currentYear})`,
    amount: 55,
    status: 'pagado',
    billingMonth: currentMonth,
    billingYear: currentYear,
    dueDate: new Date(currentYear, currentMonth - 1, 5),
    paidDate: new Date(currentYear, currentMonth - 1, 1),
    paymentMethod: 'transferencia',
    autogenerated: true,
    createdAt: new Date(currentYear, currentMonth - 1, 1),
  },
  {
    id: 'pay-015',
    playerId: 'player-003',
    playerName: 'Francisco Martínez Sánchez',
    groupId: 'group-006',
    groupName: 'Iniciación Adultos - Viernes',
    enrollmentId: 'enroll-012',
    concept: `Cuota Iniciación Adultos - Viernes (${currentMonth}/${currentYear})`,
    amount: 35,
    status: 'pendiente',
    billingMonth: currentMonth,
    billingYear: currentYear,
    dueDate: new Date(currentYear, currentMonth - 1, 5),
    autogenerated: true,
    createdAt: new Date(currentYear, currentMonth - 1, 1),
  },
]

// ===================
// ACTIVIDAD RECIENTE
// ===================
export const demoActivities: Activity[] = [
  {
    id: 'act-001',
    type: 'player_created',
    description: 'Se registró a Elena Flores Ramos en lista de espera',
    relatedEntityId: 'player-012',
    userId: 'demo-director-001',
    createdAt: new Date(currentYear, currentMonth - 1, 8),
  },
  {
    id: 'act-002',
    type: 'payment_received',
    description: 'Pago recibido de Antonio García Pérez - 55,00 € (Intermedio)',
    relatedEntityId: 'pay-007',
    userId: 'demo-director-001',
    createdAt: new Date(currentYear, currentMonth - 1, 2),
  },
  {
    id: 'act-003',
    type: 'attendance_recorded',
    description: 'Asistencia registrada para Competición - Martes/Jueves/Viernes',
    relatedEntityId: 'group-004',
    userId: 'demo-director-001',
    createdAt: new Date(currentYear, currentMonth - 1, 4),
  },
  {
    id: 'act-004',
    type: 'payment_received',
    description: 'Pago recibido de Roberto Moreno Castillo - 85,00 € (Competición)',
    relatedEntityId: 'pay-012',
    userId: 'demo-director-001',
    createdAt: new Date(currentYear, currentMonth - 1, 4),
  },
  {
    id: 'act-005',
    type: 'group_created',
    description: 'Se creó el grupo Iniciación Adultos - Viernes',
    relatedEntityId: 'group-006',
    userId: 'demo-director-001',
    createdAt: new Date(currentYear, currentMonth - 2 >= 0 ? currentMonth - 2 : 11, 20),
  },
  {
    id: 'act-006',
    type: 'recovery_used',
    description: 'Lucía Navarro Gil usó crédito de recuperación en Escuela Menores',
    relatedEntityId: 'player-010',
    userId: 'demo-director-001',
    createdAt: new Date(currentYear, currentMonth - 1, 6),
  },
  {
    id: 'act-007',
    type: 'attendance_recorded',
    description: 'Asistencia registrada para Escuela Menores - Lunes/Miércoles',
    relatedEntityId: 'group-005',
    userId: 'demo-director-001',
    createdAt: new Date(currentYear, currentMonth - 1, 6),
  },
]

// ===================
// EVENTOS
// ===================
export const demoEvents: AcademyEvent[] = [
  {
    id: 'event-001',
    name: 'Mini Torneo de Navidad',
    type: 'mini_torneo',
    date: new Date('2026-01-15'),
    startTime: '10:00',
    endTime: '14:00',
    courtIds: ['court-001', 'court-002'],
    courtNames: ['Pista 1 - Central', 'Pista 2 - Cubierta'],
    coachIds: ['coach-001', 'coach-002'],
    coachNames: ['Miguel Fernández López', 'Laura Martínez Ruiz'],
    attendeePlayerIds: [
      'player-001', 'player-002', 'player-003', 'player-004',
      'player-005', 'player-006', 'player-007', 'player-008',
    ],
    attendeePlayerNames: [
      'Antonio García Pérez', 'María López Hernández', 'Francisco Martínez Sánchez', 'Carmen Ruiz Navarro',
      'Javier Hernández Torres', 'Ana Serrano Díaz', 'Roberto Moreno Castillo', 'Isabel Vega Romero',
    ],
    price: 15,
    maxCapacity: 16,
    description: 'Torneo navideño para todos los niveles. Formato americano con rotación de parejas.',
    isActive: true,
    createdAt: new Date('2025-12-20'),
  },
  {
    id: 'event-002',
    name: 'Clinic de Bandeja',
    type: 'clinic',
    date: new Date('2026-02-20'),
    startTime: '17:00',
    endTime: '19:00',
    courtIds: ['court-001'],
    courtNames: ['Pista 1 - Central'],
    coachIds: ['coach-001'],
    coachNames: ['Miguel Fernández López'],
    attendeePlayerIds: ['player-001', 'player-002', 'player-003', 'player-004'],
    attendeePlayerNames: [
      'Antonio García Pérez', 'María López Hernández', 'Francisco Martínez Sánchez', 'Carmen Ruiz Navarro',
    ],
    price: 25,
    maxCapacity: 8,
    description: 'Clinic monográfico centrado en la técnica de bandeja y sus variantes.',
    isActive: true,
    createdAt: new Date('2026-01-25'),
  },
  {
    id: 'event-003',
    name: 'Torneo Social de Primavera',
    type: 'social',
    date: new Date('2026-03-15'),
    startTime: '09:00',
    endTime: '15:00',
    courtIds: ['court-001', 'court-002', 'court-003'],
    courtNames: ['Pista 1 - Central', 'Pista 2 - Cubierta', 'Pista 3 - Exterior'],
    coachIds: ['coach-001', 'coach-002', 'coach-003'],
    coachNames: ['Miguel Fernández López', 'Laura Martínez Ruiz', 'Alejandro Sánchez Navarro'],
    attendeePlayerIds: [
      'player-001', 'player-002', 'player-003', 'player-004', 'player-005',
      'player-006', 'player-007', 'player-008', 'player-009', 'player-010',
    ],
    attendeePlayerNames: [
      'Antonio García Pérez', 'María López Hernández', 'Francisco Martínez Sánchez', 'Carmen Ruiz Navarro',
      'Javier Hernández Torres', 'Ana Serrano Díaz', 'Roberto Moreno Castillo', 'Isabel Vega Romero',
      'Pablo Jiménez Ortega', 'Lucía Navarro Gil',
    ],
    price: 20,
    maxCapacity: 20,
    description: 'Gran torneo social de primavera abierto a todos los alumnos de la academia. Incluye almuerzo.',
    isActive: true,
    createdAt: new Date('2026-02-15'),
  },
]

// ===================
// EVALUACIONES
// ===================
export const demoEvaluations: Evaluation[] = [
  {
    id: 'eval-001',
    playerId: 'player-001',
    playerName: 'Antonio García Pérez',
    coachId: 'coach-001',
    coachName: 'Miguel Fernández López',
    date: new Date('2026-01-20'),
    blocks: [
      {
        blockKey: 'tecnico_fondo',
        scores: [
          { criterionKey: 'derecha_plana_cortada', score: 8 },
          { criterionKey: 'reves_plano_cortado', score: 7 },
          { criterionKey: 'salida_pared_derecha', score: 7 },
          { criterionKey: 'salida_pared_reves', score: 6 },
          { criterionKey: 'pared_lateral_derecha', score: 7 },
          { criterionKey: 'pared_lateral_reves', score: 6 },
          { criterionKey: 'doble_pared_abre_derecha', score: 6 },
          { criterionKey: 'doble_pared_abre_reves', score: 5 },
          { criterionKey: 'doble_pared_cierra_derecha', score: 6 },
          { criterionKey: 'doble_pared_cierra_reves', score: 5 },
          { criterionKey: 'giros_simples', score: 7 },
          { criterionKey: 'giros_doble_pared', score: 5 },
          { criterionKey: 'globos', score: 8 },
        ],
        average: 6.38,
        comment: 'Buen golpe de derecha y globo. Necesita mejorar las dobles paredes y los giros complejos.',
      },
      {
        blockKey: 'tecnico_red',
        scores: [
          { criterionKey: 'volea_derecha', score: 8 },
          { criterionKey: 'volea_reves', score: 7 },
          { criterionKey: 'dejada', score: 6 },
        ],
        average: 7.00,
        comment: 'Buenas voleas, especialmente de derecha. La dejada necesita más trabajo de muñeca.',
      },
      {
        blockKey: 'tecnico_aereo',
        scores: [
          { criterionKey: 'bandeja', score: 7 },
          { criterionKey: 'vibora', score: 6 },
          { criterionKey: 'remate_potencia', score: 7 },
          { criterionKey: 'rulo_reja', score: 5 },
          { criterionKey: 'defensa_remate', score: 6 },
        ],
        average: 6.20,
        comment: 'Bandeja y remate correctos. El rulo a la reja y la defensa de remate requieren más práctica.',
      },
      {
        blockKey: 'tecnico_saque',
        scores: [
          { criterionKey: 'saque', score: 7 },
          { criterionKey: 'resto', score: 7 },
        ],
        average: 7.00,
        comment: 'Saque consistente con buena dirección. Resto seguro.',
      },
      {
        blockKey: 'tactico',
        scores: [
          { criterionKey: 'toma_decisiones', score: 7 },
          { criterionKey: 'transicion', score: 6 },
          { criterionKey: 'velocidad_golpes', score: 7 },
          { criterionKey: 'analisis_rival', score: 6 },
          { criterionKey: 'lectura_juego', score: 7 },
        ],
        average: 6.60,
        comment: 'Buena toma de decisiones general. Debe mejorar la transición defensa-ataque y el análisis del rival.',
      },
      {
        blockKey: 'fisico_mental',
        scores: [
          { criterionKey: 'resistencia_cardio', score: 8 },
          { criterionKey: 'explosividad_agilidad', score: 7 },
          { criterionKey: 'gestion_errores', score: 6 },
          { criterionKey: 'concentracion_actitud', score: 7 },
        ],
        average: 7.00,
        comment: 'Buena condición física. La gestión de errores es el punto a mejorar mentalmente.',
      },
    ],
    overallAverage: 6.56,
    finalComment: 'Antonio muestra buen nivel general. Debe mejorar los golpes de doble pared y la gestión mental.',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-20'),
  },
  {
    id: 'eval-002',
    playerId: 'player-003',
    playerName: 'Francisco Martínez Sánchez',
    coachId: 'coach-001',
    coachName: 'Miguel Fernández López',
    date: new Date('2026-02-01'),
    blocks: [
      {
        blockKey: 'tecnico_fondo',
        scores: [
          { criterionKey: 'derecha_plana_cortada', score: 9 },
          { criterionKey: 'reves_plano_cortado', score: 8 },
          { criterionKey: 'salida_pared_derecha', score: 8 },
          { criterionKey: 'salida_pared_reves', score: 7 },
          { criterionKey: 'pared_lateral_derecha', score: 8 },
          { criterionKey: 'pared_lateral_reves', score: 7 },
          { criterionKey: 'doble_pared_abre_derecha', score: 7 },
          { criterionKey: 'doble_pared_abre_reves', score: 6 },
          { criterionKey: 'doble_pared_cierra_derecha', score: 7 },
          { criterionKey: 'doble_pared_cierra_reves', score: 6 },
          { criterionKey: 'giros_simples', score: 8 },
          { criterionKey: 'giros_doble_pared', score: 6 },
          { criterionKey: 'globos', score: 9 },
        ],
        average: 7.38,
        comment: 'Excelente derecha y globo. Las dobles paredes van progresando adecuadamente.',
      },
      {
        blockKey: 'tecnico_red',
        scores: [
          { criterionKey: 'volea_derecha', score: 9 },
          { criterionKey: 'volea_reves', score: 8 },
          { criterionKey: 'dejada', score: 7 },
        ],
        average: 8.00,
        comment: 'Voleas excelentes, muy sólido en la red. Dejada con buen toque.',
      },
      {
        blockKey: 'tecnico_aereo',
        scores: [
          { criterionKey: 'bandeja', score: 8 },
          { criterionKey: 'vibora', score: 7 },
          { criterionKey: 'remate_potencia', score: 8 },
          { criterionKey: 'rulo_reja', score: 6 },
          { criterionKey: 'defensa_remate', score: 7 },
        ],
        average: 7.20,
        comment: 'Buen juego aéreo en general. El rulo a la reja es el golpe con más margen de mejora.',
      },
      {
        blockKey: 'tecnico_saque',
        scores: [
          { criterionKey: 'saque', score: 8 },
          { criterionKey: 'resto', score: 8 },
        ],
        average: 8.00,
        comment: 'Saque potente y variado. Resto agresivo y bien colocado.',
      },
      {
        blockKey: 'tactico',
        scores: [
          { criterionKey: 'toma_decisiones', score: 8 },
          { criterionKey: 'transicion', score: 7 },
          { criterionKey: 'velocidad_golpes', score: 8 },
          { criterionKey: 'analisis_rival', score: 7 },
          { criterionKey: 'lectura_juego', score: 9 },
        ],
        average: 7.80,
        comment: 'Muy buena lectura de juego. La transición y el análisis del rival siguen mejorando.',
      },
      {
        blockKey: 'fisico_mental',
        scores: [
          { criterionKey: 'resistencia_cardio', score: 8 },
          { criterionKey: 'explosividad_agilidad', score: 8 },
          { criterionKey: 'gestion_errores', score: 7 },
          { criterionKey: 'concentracion_actitud', score: 8 },
        ],
        average: 7.75,
        comment: 'Buena forma física y mental. Mantiene la concentración durante todo el partido.',
      },
    ],
    overallAverage: 7.56,
    finalComment: 'Francisco tiene un juego muy completo. Destacan sus voleas y su lectura de juego.',
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-02-01'),
  },
]

// ===================
// CONFIGURACIÓN SALARIOS ENTRENADORES
// ===================
export const demoCoachSalaryConfigs: CoachSalaryConfig[] = [
  {
    coachId: 'coach-001',
    ratePerGroup: 250,
    ratePerPrivateLesson: 30,
    bonuses: 100,
  },
  {
    coachId: 'coach-002',
    ratePerGroup: 200,
    ratePerPrivateLesson: 25,
    bonuses: 50,
  },
  {
    coachId: 'coach-003',
    ratePerGroup: 200,
    ratePerPrivateLesson: 25,
    bonuses: 0,
  },
]
