import { onDocumentCreated } from "firebase-functions/v2/firestore";
import { getFirestore } from "firebase-admin/firestore";
import { getMessaging } from "firebase-admin/messaging";
import { logger } from "firebase-functions/v2";

// ── Notificación al crear un recibo mensual ───────────────────────────────────
// Cuando la facturación automática crea un Payment, notifica al alumno/tutor.

const MONTH_NAMES = [
  "enero","febrero","marzo","abril","mayo","junio",
  "julio","agosto","septiembre","octubre","noviembre","diciembre",
];

export const onPaymentCreated = onDocumentCreated(
  { document: "payments/{paymentId}", region: "europe-west1" },
  async (event) => {
    const payment = event.data?.data();
    if (!payment) return;

    // Solo recibos automáticos de la facturación mensual
    if (!payment.autogenerated || payment.status !== "pendiente") return;

    const db = getFirestore();
    const messaging = getMessaging();
    const { playerId, concept, amount, billingMonth, billingYear, dueDate } = payment as {
      playerId: string;
      concept: string;
      amount: number;
      billingMonth: number;
      billingYear: number;
      dueDate: FirebaseFirestore.Timestamp;
    };

    // Buscar usuarios vinculados (jugador directo o tutores)
    const tokens: string[] = [];
    const userDocIds: string[] = [];

    const [directSnap, tutorSnap] = await Promise.all([
      db.collection("users").where("linkedPlayerId", "==", playerId).limit(5).get(),
      db.collection("users").where("linkedPlayerIds", "array-contains", playerId).limit(5).get(),
    ]);

    [...directSnap.docs, ...tutorSnap.docs].forEach((doc) => {
      const fcmTokens: string[] = doc.data().fcmTokens ?? [];
      tokens.push(...fcmTokens);
      if (fcmTokens.length > 0) userDocIds.push(doc.id);
    });

    if (tokens.length === 0) return;

    const monthLabel = MONTH_NAMES[(billingMonth ?? 1) - 1] ?? "";
    const amountStr = new Intl.NumberFormat("es-ES", { style: "currency", currency: "EUR" }).format(amount ?? 0);
    const dueDateStr = dueDate ? new Date(dueDate.toMillis()).toLocaleDateString("es-ES") : "";

    const title = `🧾 Nuevo recibo disponible`;
    const body = `${concept ?? `Cuota ${monthLabel} ${billingYear}`} — ${amountStr}${dueDateStr ? `. Vence el ${dueDateStr}` : ""}`;

    const result = await messaging.sendEachForMulticast({
      tokens,
      notification: { title, body },
      data: { url: "/pagos", type: "payment_created", billingMonth: String(billingMonth), billingYear: String(billingYear) },
      webpush: {
        notification: { title, body, icon: "/pwa-192x192.png", badge: "/pwa-64x64.png", tag: `payment-${billingMonth}-${billingYear}` },
        fcmOptions: { link: "/pagos" },
      },
    });

    // Limpiar tokens inválidos
    const invalidTokens: string[] = [];
    result.responses.forEach((resp, idx) => {
      if (!resp.success && resp.error?.code === "messaging/registration-token-not-registered") {
        invalidTokens.push(tokens[idx]);
      }
    });
    if (invalidTokens.length > 0) {
      for (const docId of userDocIds) {
        const userSnap = await db.collection("users").doc(docId).get();
        const currentTokens: string[] = userSnap.data()?.fcmTokens ?? [];
        const filtered = currentTokens.filter((t) => !invalidTokens.includes(t));
        if (filtered.length !== currentTokens.length) {
          await db.collection("users").doc(docId).update({ fcmTokens: filtered });
        }
      }
    }

    logger.info(`[onPaymentCreated] Notificación enviada a ${result.successCount} dispositivos para recibo ${billingMonth}/${billingYear}`);
  }
);
