// ==========================================
// San Javier Academy Manager - Tipos de Datos
// ==========================================

// --- Club ---
export interface Club {
  id: string
  name: string
  address: string
  phone: string
  email: string
  logo?: string
  openingTime: string
  closingTime: string
  seasonStart: Date
  seasonEnd: Date
  createdAt: Date
}

// --- Pista ---
export type CourtType = 'indoor' | 'outdoor'
export type CourtSurface = 'cristal' | 'muro' | 'cesped'

export interface Court {
  id: string
  name: string
  type: CourtType
  surface: CourtSurface
  isActive: boolean
  notes?: string
}

// --- Tarifa ---
export type BillingFrequency = 'monthly' | 'installments'

export interface Tariff {
  id: string
  name: string
  price: number
  billingFrequency: BillingFrequency
  installmentMonths?: number[]
  installmentPrices?: Record<number, number>
  description?: string
  isActive: boolean
  createdAt: Date
}

// --- Usuario ---
export type UserRole = 'director' | 'coordinador' | 'entrenador' | 'jugador' | 'tutor'

export interface AppUser {
  id: string
  email: string
  displayName: string
  role: UserRole
  clubId: string
  linkedPlayerId?: string
  linkedPlayerIds?: string[]
  isActive: boolean
  createdAt: Date
}

// --- Jugador ---
export type PlayerLevel = 'iniciacion' | 'intermedio' | 'avanzado' | 'competicion' | 'menores'
export type PlayerStatus = 'activo' | 'lista_espera' | 'baja'
export type DominantHand = 'derecha' | 'izquierda'
export type PlayerPosition = 'drive' | 'reves' | 'ambos'
export type GuardianRelationship = 'padre' | 'madre' | 'tutor'

export interface Guardian {
  firstName: string
  lastName: string
  dni: string
  phone: string
  email: string
  relationship: GuardianRelationship
}

export interface Player {
  id: string
  // Datos personales
  firstName: string
  lastName: string
  dni: string
  birthDate: Date
  email: string
  phone: string
  address: string
  city: string
  postalCode: string
  photo?: string
  // Datos deportivos
  level: PlayerLevel
  dominantHand: DominantHand
  position: PlayerPosition
  previousExperience?: string
  medicalNotes?: string
  // Datos bancarios
  bankAccountHolder: string
  iban: string
  // Estado
  status: PlayerStatus
  registrationDate: Date
  cancellationDate?: Date
  // Menor de edad
  isMinor: boolean
  guardian?: Guardian
  // Recuperaciones
  recoveryCredits: number
  // Metadata
  notes?: string
  userId?: string
  createdAt: Date
  updatedAt: Date
}

// --- Entrenador ---
export type StaffRole = 'entrenador' | 'coordinador' | 'director'

export interface Coach {
  id: string
  firstName: string
  lastName: string
  dni: string
  email: string
  phone: string
  address?: string
  hireDate: Date
  isActive: boolean
  specialization?: string
  certifications?: string
  photo?: string
  userId?: string
  staffRole?: StaffRole
  notes?: string
  createdAt: Date
}

// --- Grupo ---
export interface ScheduleSlot {
  dayOfWeek: number
  startTime: string
  endTime: string
}

export interface Group {
  id: string
  name: string
  level: PlayerLevel
  coachId: string
  coachName: string
  courtId: string
  courtName: string
  schedule: ScheduleSlot[]
  maxCapacity: number
  currentEnrollment: number
  defaultTariffId: string
  defaultTariffPrice: number
  billingFrequency: BillingFrequency
  installmentMonths?: number[]
  startDate: Date
  endDate: Date
  isActive: boolean
  createdAt: Date
}

// --- Inscripción ---
export interface Enrollment {
  id: string
  playerId: string
  playerName: string
  groupId: string
  groupName: string
  tariffId: string
  tariffName: string
  customPrice?: number
  enrollmentDate: Date
  unenrollmentDate?: Date
  isActive: boolean
}

// --- Asistencia ---
export type AttendanceStatus = 'presente' | 'ausente' | 'justificado'

export interface AttendanceEntry {
  playerId: string
  playerName: string
  status: AttendanceStatus
  isRecovery: boolean
  originalGroupId?: string
  notes?: string
}

export interface AttendanceRecord {
  id: string
  groupId: string
  groupName: string
  date: Date
  records: AttendanceEntry[]
  coachId: string
  createdAt: Date
}

// --- Pago ---
export type PaymentStatus = 'pendiente' | 'pagado' | 'cancelado'
export type PaymentMethod = 'transferencia' | 'efectivo' | 'domiciliacion' | 'tarjeta'
export type PaymentCategory = 'cuota' | 'evento' | 'clase_particular' | 'manual' | 'otro'

export interface Payment {
  id: string
  playerId: string
  playerName: string
  groupId?: string
  groupName?: string
  enrollmentId?: string
  concept: string
  category?: PaymentCategory
  amount: number
  status: PaymentStatus
  billingMonth: number
  billingYear: number
  dueDate: Date
  paidDate?: Date
  paymentMethod?: PaymentMethod
  notes?: string
  autogenerated: boolean
  createdAt: Date
}

// --- Clase Particular ---
export interface PrivateLesson {
  id: string
  playerIds: string[]
  playerNames: string[]
  coachId: string
  coachName: string
  courtId: string
  courtName: string
  date: Date
  startTime: string
  endTime: string
  price: number
  isPaid: boolean
  notes?: string
  createdAt: Date
}

// --- Actividad ---
export type ActivityType =
  | 'player_created'
  | 'player_cancelled'
  | 'payment_received'
  | 'group_created'
  | 'attendance_recorded'
  | 'recovery_used'
  | 'evaluation_created'
  | 'event_created'
  | 'invitation_sent'

export interface Activity {
  id: string
  type: ActivityType
  description: string
  relatedEntityId?: string
  userId: string
  createdAt: Date
}

// --- Invitación ---
export type InvitationStatus = 'pendiente' | 'aceptada' | 'expirada'

export interface Invitation {
  id: string
  email: string
  role: UserRole
  linkedPlayerId?: string
  linkedPlayerIds?: string[]
  clubId: string
  status: InvitationStatus
  token: string
  createdBy: string
  createdAt: Date
  expiresAt: Date
  acceptedAt?: Date
}

// --- Evento (mini torneos, clinics, etc.) ---
export type EventType = 'mini_torneo' | 'clinic' | 'exhibicion' | 'social'

export interface AcademyEvent {
  id: string
  name: string
  type: EventType
  date: Date
  startTime: string
  endTime: string
  courtIds: string[]
  courtNames: string[]
  coachIds: string[]
  coachNames: string[]
  attendeePlayerIds: string[]
  attendeePlayerNames: string[]
  price: number
  maxCapacity?: number
  description?: string
  guestNames?: string[]
  isActive: boolean
  createdAt: Date
}

// --- Pago de Evento ---
export interface EventPayment {
  id: string
  eventId: string
  eventName: string
  playerId: string
  playerName: string
  amount: number
  status: PaymentStatus
  paymentMethod?: PaymentMethod
  paidDate?: Date
  createdAt: Date
}

// --- Evaluación / Informe ---
export interface EvaluationScore {
  criterionKey: string
  score: number
}

export interface EvaluationBlock {
  blockKey: string
  scores: EvaluationScore[]
  average: number
  comment?: string
}

export interface Evaluation {
  id: string
  playerId: string
  playerName: string
  coachId: string
  coachName: string
  date: Date
  blocks: EvaluationBlock[]
  overallAverage: number
  finalComment?: string
  createdAt: Date
  updatedAt: Date
}

// --- Informe de Partido ---
export interface MatchReport {
  id: string
  title: string
  date: Date
  playerIds: string[]
  playerNames: string[]
  coachId: string
  coachName: string
  // Sections
  tacticsComment: string       // Táctica
  decisionMakingComment: string // Toma de decisiones
  mentalComment: string         // Aspecto mental
  generalComment?: string       // Comentario general
  createdAt: Date
  updatedAt: Date
}

// --- Configuración Salario Entrenador ---
export interface CoachSalaryConfig {
  coachId: string
  ratePerGroup: number
  ratePerPrivateLesson: number
  bonuses: number
  notes?: string
}
